"""add softdelete columns to patients

Revision ID: 15d322fa7a61
Revises: 614fb24706f0
Create Date: 2026-01-30 16:11:38.395818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15d322fa7a61'
down_revision: Union[str, Sequence[str], None] = '614fb24706f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('patients', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'deleted_at')
    op.drop_column('patients', 'is_deleted')
    # ### end Alembic commands ###
