"""Improved all tables

Revision ID: 3f4f2bb783e3
Revises: 042f081e4a99
Create Date: 2026-02-28 15:28:00.507018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3f4f2bb783e3'
down_revision: Union[str, Sequence[str], None] = '042f081e4a99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hospitals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospitals_code'), 'hospitals', ['code'], unique=True)
    op.create_table('qualifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('specializations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line1', sa.String(length=255), nullable=False),
    sa.Column('line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('line1', 'line2', 'city', 'state', 'postal_code', 'country', name='uq_full_address')
    )
    op.create_table('admissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('admission_date', sa.DateTime(), nullable=False),
    sa.Column('discharge_date', sa.DateTime(), nullable=True),
    sa.Column('ward', sa.String(length=50), nullable=True),
    sa.Column('room_number', sa.String(length=20), nullable=True),
    sa.Column('bed_number', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'DISCHARGED', 'CANCELLED', name='admissionstatus'), nullable=False),
    sa.Column('admitted_by', sa.Integer(), nullable=True),
    sa.Column('reason_for_admission', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['admitted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hospital_id', 'patient_id', 'admission_date', name='uq_patient_admission')
    )
    op.create_table('allergies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('reaction', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hospital_id', 'patient_id', 'name', name='uq_patient_allergy')
    )
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('person_type', sa.Enum('User', 'Patient', name='persontype'), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('country_code', sa.String(length=5), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('relation', sa.String(length=50), nullable=True),
    sa.Column('contact_type', sa.Enum('Emergency', 'Guardian', 'Other', name='contacttype'), nullable=False),
    sa.Column('preferred_contact', sa.Boolean(), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_type', 'person_id', 'contact_type', 'phone', name='uq_person_contact')
    )
    op.create_table('insurances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(length=100), nullable=False),
    sa.Column('policy_number', sa.String(length=50), nullable=False),
    sa.Column('coverage_type', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'provider_name', 'policy_number', name='uq_patient_insurance')
    )
    op.create_table('medications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('dosage', sa.String(length=50), nullable=True),
    sa.Column('frequency', sa.String(length=50), nullable=True),
    sa.Column('route', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hospital_id', 'patient_id', 'name', name='uq_patient_medication')
    )
    op.create_table('surgeries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('surgeon_id', sa.Integer(), nullable=True),
    sa.Column('anesthesia_type', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['surgeon_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hospital_id', 'patient_id', 'name', 'date', name='uq_patient_surgery')
    )
    op.add_column('patients', sa.Column('hospital_id', sa.Integer(), nullable=False))
    op.add_column('patients', sa.Column('address_id', sa.Integer(), nullable=True))
    op.add_column('patients', sa.Column('blood_group', sa.Enum('A_POS', 'A_NEG', 'B_POS', 'B_NEG', 'AB_POS', 'AB_NEG', 'O_POS', 'O_NEG', 'UNKNOWN', name='bloodgroup'), nullable=True))
    op.add_column('patients', sa.Column('marital_status', sa.Enum('SINGLE', 'MARRIED', 'DIVORCED', 'WIDOWED', 'OTHER', name='maritalstatus'), nullable=True))
    op.add_column('patients', sa.Column('organ_donor', sa.Boolean(), nullable=True))
    op.add_column('patients', sa.Column('preferred_language', sa.String(length=50), nullable=True))
    op.add_column('patients', sa.Column('occupation', sa.String(length=100), nullable=True))
    op.add_column('patients', sa.Column('created_by', sa.String(length=255), nullable=True))
    op.add_column('patients', sa.Column('updated_by', sa.String(length=255), nullable=True))
    op.add_column('patients', sa.Column('deleted_by', sa.String(length=255), nullable=True))
    op.alter_column('patients', 'gender',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender'),
               existing_nullable=False)
    op.drop_index(op.f('email'), table_name='patients')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_index(op.f('phone_number'), table_name='patients')
    op.drop_index(op.f('ix_patients_mrn'), table_name='patients')
    op.create_index(op.f('ix_patients_mrn'), 'patients', ['mrn'], unique=False)
    op.create_index(op.f('ix_patients_email'), 'patients', ['email'], unique=False)
    op.create_index(op.f('ix_patients_hospital_id'), 'patients', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_patients_phone_number'), 'patients', ['phone_number'], unique=False)
    op.create_unique_constraint('uq_hospital_email', 'patients', ['hospital_id', 'email'])
    op.create_unique_constraint('uq_hospital_mrn', 'patients', ['hospital_id', 'mrn'])
    op.create_unique_constraint('uq_hospital_phone', 'patients', ['hospital_id', 'phone_number'])
    op.create_foreign_key(None, 'patients', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'patients', 'addresses', ['address_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'patients', 'users', ['deleted_by'], ['id'])
    op.create_foreign_key(None, 'patients', 'hospitals', ['hospital_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'patients', 'users', ['updated_by'], ['id'])
    op.drop_column('patients', 'address')
    op.add_column('revoked_tokens', sa.Column('created_by', sa.String(length=255), nullable=True))
    op.add_column('revoked_tokens', sa.Column('updated_by', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'revoked_tokens', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'revoked_tokens', 'users', ['updated_by'], ['id'])
    op.add_column('users', sa.Column('staff_id', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('hospital_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('department_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('qualification_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('specialization_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('experience_years', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('shift_start', sa.Time(timezone=True), nullable=True))
    op.add_column('users', sa.Column('shift_end', sa.Time(timezone=True), nullable=True))
    op.add_column('users', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('two_factor_enabled', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('national_id', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('profile_photo', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('users', 'phone_number',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('users', 'date_of_birth',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=False)
    op.create_index(op.f('ix_users_hospital_id'), 'users', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_users_national_id'), 'users', ['national_id'], unique=False)
    op.create_index(op.f('ix_users_staff_id'), 'users', ['staff_id'], unique=False)
    op.create_unique_constraint('uq_user_hospital_email', 'users', ['hospital_id', 'email'])
    op.create_unique_constraint('uq_user_hospital_national_id', 'users', ['hospital_id', 'national_id'])
    op.create_unique_constraint('uq_user_hospital_phone', 'users', ['hospital_id', 'phone_number'])
    op.create_unique_constraint('uq_user_hospital_staff', 'users', ['hospital_id', 'staff_id'])
    op.create_foreign_key(None, 'users', 'specializations', ['specialization_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'users', 'users', ['deleted_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'users', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'users', 'qualifications', ['qualification_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'users', 'hospitals', ['hospital_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'users', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'users', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
    op.drop_column('users', 'address')
    op.drop_column('users', 'department')
    op.drop_column('users', 'failed_attempts')
    op.drop_column('users', 'account_locked_until')
    op.drop_column('users', 'profile_picture')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_picture', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('users', sa.Column('account_locked_until', mysql.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('failed_attempts', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('department', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('users', sa.Column('address', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint('uq_user_hospital_staff', 'users', type_='unique')
    op.drop_constraint('uq_user_hospital_phone', 'users', type_='unique')
    op.drop_constraint('uq_user_hospital_national_id', 'users', type_='unique')
    op.drop_constraint('uq_user_hospital_email', 'users', type_='unique')
    op.drop_index(op.f('ix_users_staff_id'), table_name='users')
    op.drop_index(op.f('ix_users_national_id'), table_name='users')
    op.drop_index(op.f('ix_users_hospital_id'), table_name='users')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.alter_column('users', 'date_of_birth',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('users', 'phone_number',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=15),
               existing_nullable=False)
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'is_deleted')
    op.drop_column('users', 'profile_photo')
    op.drop_column('users', 'national_id')
    op.drop_column('users', 'two_factor_enabled')
    op.drop_column('users', 'password_changed_at')
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'shift_end')
    op.drop_column('users', 'shift_start')
    op.drop_column('users', 'experience_years')
    op.drop_column('users', 'specialization_id')
    op.drop_column('users', 'qualification_id')
    op.drop_column('users', 'department_id')
    op.drop_column('users', 'deleted_by')
    op.drop_column('users', 'updated_by')
    op.drop_column('users', 'created_by')
    op.drop_column('users', 'hospital_id')
    op.drop_column('users', 'staff_id')
    op.drop_constraint(None, 'revoked_tokens', type_='foreignkey')
    op.drop_constraint(None, 'revoked_tokens', type_='foreignkey')
    op.drop_column('revoked_tokens', 'updated_by')
    op.drop_column('revoked_tokens', 'created_by')
    op.add_column('patients', sa.Column('address', mysql.VARCHAR(length=500), nullable=True))
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_constraint('uq_hospital_phone', 'patients', type_='unique')
    op.drop_constraint('uq_hospital_mrn', 'patients', type_='unique')
    op.drop_constraint('uq_hospital_email', 'patients', type_='unique')
    op.drop_index(op.f('ix_patients_phone_number'), table_name='patients')
    op.drop_index(op.f('ix_patients_hospital_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_email'), table_name='patients')
    op.drop_index(op.f('ix_patients_mrn'), table_name='patients')
    op.create_index(op.f('ix_patients_mrn'), 'patients', ['mrn'], unique=True)
    op.create_index(op.f('phone_number'), 'patients', ['phone_number'], unique=True)
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.create_index(op.f('email'), 'patients', ['email'], unique=True)
    op.alter_column('patients', 'gender',
               existing_type=sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender'),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_column('patients', 'deleted_by')
    op.drop_column('patients', 'updated_by')
    op.drop_column('patients', 'created_by')
    op.drop_column('patients', 'occupation')
    op.drop_column('patients', 'preferred_language')
    op.drop_column('patients', 'organ_donor')
    op.drop_column('patients', 'marital_status')
    op.drop_column('patients', 'blood_group')
    op.drop_column('patients', 'address_id')
    op.drop_column('patients', 'hospital_id')
    op.drop_table('surgeries')
    op.drop_table('medications')
    op.drop_table('insurances')
    op.drop_table('contacts')
    op.drop_table('allergies')
    op.drop_table('admissions')
    op.drop_table('addresses')
    op.drop_table('specializations')
    op.drop_table('qualifications')
    op.drop_index(op.f('ix_hospitals_code'), table_name='hospitals')
    op.drop_table('hospitals')
    op.drop_table('departments')
    # ### end Alembic commands ###
