"""add mrn to patient

Revision ID: 656c4e9b8073
Revises: 15d322fa7a61
Create Date: 2026-01-30 18:31:42.379866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '656c4e9b8073'
down_revision: Union[str, Sequence[str], None] = '15d322fa7a61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('mrn', sa.String(length=20), nullable=False))
    op.create_index(op.f('ix_patients_mrn'), 'patients', ['mrn'], unique=True)
    op.alter_column('users', 'role',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('SUPER_ADMIN', 'ADMIN', 'DOCTOR', 'NURSE', 'RECEPTIONIST', name='userrole'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('SUPER_ADMIN', 'ADMIN', 'DOCTOR', 'NURSE', 'RECEPTIONIST', name='userrole'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_patients_mrn'), table_name='patients')
    op.drop_column('patients', 'mrn')
    # ### end Alembic commands ###
